/*
 * Decompiled with CFR 0.152.
 */
public final class c {
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public boolean a = false;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;
    public int b;
    public int c;
    int d;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;

    public final void a(b b2) {
        b2.d = this.h;
        b2.e = this.i;
        b2.f = this.j;
        b2.g = this.k;
        b2.h = this.l;
        b2.i = this.m;
        b2.j = this.n;
        b2.k = this.o;
        b2.l = this.p;
        b2.m = this.q;
        b2.n = this.r;
        b2.o = this.s;
        b2.p = this.t;
        b2.leftMargin = this.A;
        b2.rightMargin = this.B;
        b2.topMargin = this.C;
        b2.bottomMargin = this.D;
        b2.u = this.M;
        b2.v = this.L;
        b2.w = this.u;
        b2.x = this.v;
        b2.y = this.w;
        b2.K = this.x;
        b2.L = this.y;
        b2.B = this.N;
        b2.A = this.O;
        b2.D = this.Q;
        b2.C = this.P;
        b2.E = this.ad;
        b2.F = this.ae;
        b2.I = this.af;
        b2.J = this.ag;
        b2.G = this.ah;
        b2.H = this.ai;
        b2.M = this.z;
        b2.c = this.g;
        b2.a = this.e;
        b2.b = this.f;
        b2.width = this.b;
        b2.height = this.c;
        b2.setMarginStart(this.F);
        b2.setMarginEnd(this.E);
        b2.a();
    }
}

