/*
 * Decompiled with CFR 0.152.
 */
public final class dxv {
    public static final dyo A;
    public static final dyo B;
    public static final dyo C;
    public static final dyo D;
    public static final dyo E;
    public static final dyo F;
    public static final dyo G;
    public static final dyo H;
    public static final dyo I;
    public static final dyo J;
    public static final dyo K;
    public static final dyo L;
    public static final dyo M;
    public static final dyo N;
    public static final dyo O;
    public static final dyo P;
    public static final dyo Q;
    public static final dyo R;
    public static final dyo S;
    public static final dyo T;
    public static final dyo U;
    public static final dyo V;
    public static final dyo W;
    public static final dyo X;
    public static final dyo Y;
    public static final dyo Z;
    public static final dyo a;
    public static final dyo aA;
    public static final dyo aB;
    public static final dyo aC;
    public static final dyo aD;
    public static final dyo aE;
    public static final dyo aF;
    public static final dyo aG;
    public static final dyn aH;
    public static final dyo aI;
    public static final dyo aJ;
    public static final dyo aK;
    public static final dyo aL;
    public static final dyo aM;
    public static final dyo aN;
    public static final dyo aO;
    public static final dyo aP;
    public static final dyo aQ;
    public static final dyn aR;
    public static final dyo aS;
    public static final dyn aT;
    private static final dyf aU;
    private static final hav aV;
    private static final String aW;
    public static final dyo aa;
    public static final dyo ab;
    public static final dyo ac;
    public static final dyo ad;
    public static final dyo ae;
    public static final dyo af;
    public static final dyo ag;
    public static final dyo ah;
    public static final dyn ai;
    public static final dyo aj;
    public static final dyn ak;
    public static final dyo al;
    public static final dyo am;
    public static final dyn an;
    public static final dyo ao;
    public static final dyo ap;
    public static final dyo aq;
    public static final dyn ar;
    public static final dyo as;
    public static final dyn at;
    public static final dyo au;
    public static final dyn av;
    public static final dyo aw;
    public static final dyn ax;
    public static final dyo ay;
    public static final dyn az;
    public static final dyo b;
    public static final dyn c;
    public static final dyo d;
    public static final dyo e;
    public static final dyo f;
    public static final dyo g;
    public static final dyo h;
    public static final dyn i;
    public static final dyo j;
    public static final dyo k;
    public static final dyo l;
    public static final dyo m;
    public static final dyo n;
    public static final dyo o;
    public static final dyo p;
    public static final dyo q;
    public static final dyo r;
    public static final dyo s;
    public static final dyo t;
    public static final dyo u;
    public static final dyo v;
    public static final dyn w;
    public static final dyo x;
    public static final dyo y;
    public static final dyo z;

    static {
        aU = new dyf(1673, a.z(0));
        aV = hav.p(1, 1673);
        aW = "com.google.android.libraries.search.appflows.apps.searchtranscriptionandroid.FlowEventsProto.FlowEvent";
        dxv.a("UNKNOWN_EVENT", 0, dxw.b, false, gsl.a);
        dxv.a("META_START_EVENT", 1, dxw.b, false, gsl.a);
        dxv.a("META_END_EVENT", 2, dxw.b, false, gsl.a);
        Object object = dxw.c;
        Object object2 = 3600000L;
        a = dxv.a("INTENT_API_START", 101, (dyg)object, true, gto.i(object2));
        b = dxv.a("INTENT_API_USER_RETRY", 102, dxw.c, true, gto.i(object2));
        Object object3 = dxw.c;
        object = gsl.a;
        c = dxv.b("INTENT_API_FINISH", 103, (dyg)object3, new int[]{101, 102}, (gto)object);
        d = dxv.a("INTENT_API_START_OF_SPEECH", 104, dxw.b, false, gsl.a);
        e = dxv.a("INTENT_API_END_OF_SPEECH", 105, dxw.b, false, gsl.a);
        f = dxv.a("INTENT_API_MIC_OPENED", 106, dxw.b, false, gsl.a);
        g = dxv.a("INTENT_API_MIC_CLOSE_REQUESTED", 107, dxw.b, false, gsl.a);
        object3 = dxw.d;
        object = 86400000L;
        h = dxv.a("RECOGNITION_SERVICE_START", 108, (dyg)object3, true, gto.i(object));
        object3 = dxw.d;
        Object object4 = gsl.a;
        i = dxv.b("RECOGNITION_SERVICE_FINISH", 109, (dyg)object3, new int[]{108}, (gto)object4);
        j = dxv.a("RECOGNITION_SERVICE_START_OF_SPEECH", 110, dxw.b, false, gsl.a);
        k = dxv.a("RECOGNITION_SERVICE_END_OF_SPEECH", 111, dxw.b, false, gsl.a);
        l = dxv.a("RECOGNITION_SERVICE_MIC_OPENED", 112, dxw.b, false, gsl.a);
        m = dxv.a("RECOGNITION_SERVICE_MIC_CLOSE_REQUESTED", 113, dxw.b, false, gsl.a);
        n = dxv.a("RECOGNITION_SERVICE_PREFER_OFFLINE", 114, dxw.b, false, gsl.a);
        o = dxv.a("RECOGNITION_SERVICE_AUDIO_SOURCE", 115, dxw.b, false, gsl.a);
        p = dxv.a("INTENT_API_PREFER_OFFLINE", 116, dxw.b, false, gsl.a);
        q = dxv.a("INTENT_API_AUDIO_RECORDING_REQUESTED", 117, dxw.b, false, gsl.a);
        r = dxv.a("RECOGNITION_SERVICE_MIC_DEACTIVATED", 118, dxw.b, false, gsl.a);
        s = dxv.a("INTENT_API_MIC_DEACTIVATED", 119, dxw.b, false, gsl.a);
        t = dxv.a("RECOGNITION_SERVICE_FALLBACK", 120, dxw.b, false, gsl.a);
        u = dxv.a("INTENT_API_FALLBACK", 121, dxw.b, false, gsl.a);
        v = dxv.a("VOICE_IME_START", 122, dxw.e, true, gto.i(object2));
        object3 = dxw.e;
        object4 = gsl.a;
        w = dxv.b("VOICE_IME_FINISH", 123, (dyg)object3, new int[]{122}, (gto)object4);
        x = dxv.a("VOICE_IME_RECOGNITION_START", 124, dxw.b, false, gsl.a);
        y = dxv.a("VOICE_IME_RECOGNITION_FINISH", 125, dxw.b, false, gsl.a);
        z = dxv.a("VOICE_IME_RECOGNITION_FALLBACK", 126, dxw.b, false, gsl.a);
        A = dxv.a("MANAGER_GET_SUPPORTED_PACKS", 127, dxw.b, false, gsl.a);
        B = dxv.a("MANAGER_GET_INSTALLED_PACKS", 128, dxw.b, false, gsl.a);
        C = dxv.a("MANAGER_GET_PENDING_PACKS", 129, dxw.b, false, gsl.a);
        D = dxv.a("MANAGER_INSTALL_PACK", 130, dxw.b, false, gsl.a);
        E = dxv.a("MANAGER_UNINSTALL_PACK", 131, dxw.b, false, gsl.a);
        F = dxv.a("MANAGER_GET_PACK", 132, dxw.b, false, gsl.a);
        G = dxv.a("MANAGER_GET_SUPPORTED_PACKS_DONE", 133, dxw.b, false, gsl.a);
        H = dxv.a("MANAGER_GET_INSTALLED_PACKS_DONE", 134, dxw.b, false, gsl.a);
        I = dxv.a("MANAGER_GET_PENDING_PACKS_DONE", 135, dxw.b, false, gsl.a);
        J = dxv.a("MANAGER_INSTALL_PACK_DONE", 136, dxw.b, false, gsl.a);
        K = dxv.a("MANAGER_UNINSTALL_PACK_DONE", 137, dxw.b, false, gsl.a);
        L = dxv.a("MANAGER_GET_PACK_DONE", 138, dxw.b, false, gsl.a);
        M = dxv.a("ZIPFILE_GET_SUPPORTED_PACKS", 139, dxw.b, false, gsl.a);
        N = dxv.a("ZIPFILE_GET_SUPPORTED_PACKS_DONE", 140, dxw.b, false, gsl.a);
        O = dxv.a("ZIPFILE_GET_INSTALLED_PACKS", 141, dxw.b, false, gsl.a);
        P = dxv.a("ZIPFILE_GET_INSTALLED_PACKS_DONE", 142, dxw.b, false, gsl.a);
        Q = dxv.a("ZIPFILE_GET_PENDING_PACKS", 143, dxw.b, false, gsl.a);
        R = dxv.a("ZIPFILE_GET_PENDING_PACKS_DONE", 144, dxw.b, false, gsl.a);
        S = dxv.a("ZIPFILE_INSTALL_PACK", 145, dxw.b, false, gsl.a);
        T = dxv.a("ZIPFILE_INSTALL_PACK_DONE", 146, dxw.b, false, gsl.a);
        U = dxv.a("ZIPFILE_UNINSTALL_PACK", 147, dxw.b, false, gsl.a);
        V = dxv.a("ZIPFILE_UNINSTALL_PACK_DONE", 148, dxw.b, false, gsl.a);
        W = dxv.a("ZIPFILE_GET_PACK", 149, dxw.b, false, gsl.a);
        X = dxv.a("ZIPFILE_GET_PACK_DONE", 150, dxw.b, false, gsl.a);
        Y = dxv.a("SYSTEM_GET_SUPPORTED_PACKS", 151, dxw.b, false, gsl.a);
        Z = dxv.a("SYSTEM_GET_SUPPORTED_PACKS_DONE", 152, dxw.b, false, gsl.a);
        aa = dxv.a("SYSTEM_GET_INSTALLED_PACKS", 153, dxw.b, false, gsl.a);
        ab = dxv.a("SYSTEM_GET_INSTALLED_PACKS_DONE", 154, dxw.b, false, gsl.a);
        ac = dxv.a("SYSTEM_GET_PACK", 155, dxw.b, false, gsl.a);
        ad = dxv.a("SYSTEM_GET_PACK_DONE", 156, dxw.b, false, gsl.a);
        ae = dxv.a("REQUEST_LOCALE", 157, dxw.b, false, gsl.a);
        af = dxv.a("DEREQUEST_LOCALE", 158, dxw.b, false, gsl.a);
        ag = dxv.a("SET_BACKGROUND_DOWNLOAD_CONDITION", 159, dxw.b, false, gsl.a);
        ah = dxv.a("BACKGROUND_SYNC_START", 160, dxw.f, true, gto.i(object2));
        object4 = dxw.f;
        object3 = gsl.a;
        ai = dxv.b("BACKGROUND_SYNC_END", 161, (dyg)object4, new int[]{160}, (gto)object3);
        aj = dxv.a("INTENT_GET_LANGUAGE_DETAILS_START", 162, dxw.h, true, gto.i(object2));
        object3 = dxw.h;
        object4 = gsl.a;
        ak = dxv.b("INTENT_GET_LANGUAGE_DETAILS_END", 163, (dyg)object3, new int[]{162}, (gto)object4);
        al = dxv.a("INTENT_DOWNLOAD_LANGUAGE_START", 164, dxw.g, true, gto.i(object2));
        am = dxv.a("INTENT_DOWNLOAD_LANGUAGE_SHOW_DIALOG", 165, dxw.b, false, gsl.a);
        object4 = dxw.g;
        object3 = gsl.a;
        an = dxv.b("INTENT_DOWNLOAD_LANGUAGE_END", 166, (dyg)object4, new int[]{164}, (gto)object3);
        ao = dxv.a("SETTINGS_PACK_DOWNLOAD_START", 167, dxw.l, true, gto.i(object2));
        ap = dxv.a("SETTINGS_PACK_UPDATE_START", 168, dxw.l, true, gto.i(object2));
        aq = dxv.a("SETTINGS_PACK_UNINSTALL_START", 169, dxw.l, true, gto.i(object2));
        object4 = dxw.l;
        object3 = gsl.a;
        ar = dxv.b("SETTINGS_PACK_DIALOG_END", 170, (dyg)object4, new int[]{167, 168, 169}, (gto)object3);
        as = dxv.a("SETTINGS_SET_DOWNLOAD_CONDITION_START", 171, dxw.i, true, gto.i(object2));
        object3 = dxw.i;
        object4 = gsl.a;
        at = dxv.b("SETTINGS_SET_DOWNLOAD_CONDITION_END", 172, (dyg)object3, new int[]{171}, (gto)object4);
        object4 = dxw.k;
        object3 = 60000L;
        au = dxv.a("SETTINGS_LOAD_DOWNLOADED_PACK_LIST_START", 173, (dyg)object4, true, gto.i(object3));
        object4 = dxw.k;
        gsl gsl2 = gsl.a;
        av = dxv.b("SETTINGS_LOAD_DOWNLOADED_PACK_LIST_END", 174, (dyg)object4, new int[]{173}, gsl2);
        aw = dxv.a("SETTINGS_LOAD_AVAILABLE_PACK_LIST_START", 175, dxw.j, true, gto.i(object3));
        object3 = dxw.j;
        object4 = gsl.a;
        ax = dxv.b("SETTINGS_LOAD_AVAILABLE_PACK_LIST_END", 176, (dyg)object3, new int[]{175}, (gto)object4);
        dxv.a("DICTATION_QUALITY_METRICS_START", 177, dxw.m, true, gto.i(object2));
        object4 = dxw.m;
        object3 = gsl.a;
        dxv.b("DICTATION_QUALITY_METRICS_END", 178, (dyg)object4, new int[]{177}, (gto)object3);
        ay = dxv.a("MODEL_MANAGER_CHECK_RECOGNITION_SUPPORT_START", 179, dxw.n, true, gto.i(object2));
        object4 = dxw.n;
        object3 = gsl.a;
        az = dxv.b("MODEL_MANAGER_CHECK_RECOGNITION_SUPPORT_END", 180, (dyg)object4, new int[]{179}, (gto)object3);
        aA = dxv.a("MODEL_MANAGER_GET_SUPPORTED_PACKS_START", 181, dxw.b, false, gsl.a);
        aB = dxv.a("MODEL_MANAGER_GET_SUPPORTED_PACKS_END", 182, dxw.b, false, gsl.a);
        aC = dxv.a("MODEL_MANAGER_GET_PENDING_PACKS_START", 183, dxw.b, false, gsl.a);
        aD = dxv.a("MODEL_MANAGER_GET_PENDING_PACKS_END", 184, dxw.b, false, gsl.a);
        aE = dxv.a("MODEL_MANAGER_GET_INSTALLED_PACKS_START", 185, dxw.b, false, gsl.a);
        aF = dxv.a("MODEL_MANAGER_GET_INSTALLED_PACKS_END", 186, dxw.b, false, gsl.a);
        aG = dxv.a("MODEL_MANAGER_TRIGGER_MODEL_DOWNLOAD_START", 187, dxw.o, true, gto.i(object2));
        object3 = dxw.o;
        object4 = gsl.a;
        aH = dxv.b("MODEL_MANAGER_TRIGGER_MODEL_DOWNLOAD_END", 188, (dyg)object3, new int[]{187}, (gto)object4);
        aI = dxv.a("MODEL_MANAGER_CHECK_MATCHING_PACK_START", 189, dxw.b, false, gsl.a);
        aJ = dxv.a("MODEL_MANAGER_CHECK_MATCHING_PACK_END", 190, dxw.b, false, gsl.a);
        dxv.a("MODEL_MANAGER_SHOW_DIALOG_START", 191, dxw.b, false, gsl.a);
        dxv.a("MODEL_MANAGER_SHOW_DIALOG_END", 192, dxw.b, false, gsl.a);
        aK = dxv.a("MODEL_MANAGER_SCHEDULE_DONWLOAD_START", 193, dxw.b, false, gsl.a);
        aL = dxv.a("MODEL_MANAGER_SCHEDULE_DONWLOAD_END", 194, dxw.b, false, gsl.a);
        aM = dxv.a("MODEL_MANAGER_DOWNLOAD_START", 195, dxw.b, false, gsl.a);
        aN = dxv.a("MODEL_MANAGER_DOWNLOAD_END", 196, dxw.b, false, gsl.a);
        aO = dxv.a("RECOGNITION_GRPC_SERVICE_START", 198, dxw.p, true, gto.i(object));
        aP = dxv.a("RECOGNITION_SERVICE_FIRST_START_OF_SPEECH", 199, dxw.b, false, gsl.a);
        aQ = dxv.a("RECOGNITION_SERVICE_FIRST_RECOGNITION_TEXT", 200, dxw.b, false, gsl.a);
        object3 = dxw.p;
        object = gsl.a;
        aR = dxv.b("RECOGNITION_GRPC_SERVICE_FINISH", 201, (dyg)object3, new int[]{198}, (gto)object);
        aS = dxv.a("INTENT_API_COUNT_START", 202, dxw.q, true, gto.i(object2));
        object2 = dxw.q;
        object = gsl.a;
        aT = dxv.b("INTENT_API_COUNT_FINISH", 203, (dyg)object2, new int[]{202}, (gto)object);
    }

    private static dyo a(String string, int n2, dyg dyg2, boolean bl2, gto gto2) {
        dyf dyf2 = aU;
        hav hav2 = aV;
        String string2 = aW;
        return new dyo(new dxx(string, bl2, gto2, n2, dyg2, new int[0], dyf2, hav2, string2));
    }

    private static dyn b(String string, int n2, dyg dyg2, int[] nArray, gto gto2) {
        return new dyn(new dxx(string, false, gto2, n2, dyg2, nArray, aU, aV, aW));
    }
}

