/*
 * Decompiled with CFR 0.152.
 */
import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

public final class eyg {
    public static final hac a;

    static {
        Object object = new gzy();
        ((gzy)object).d(eyf.d, "google_app.test");
        ((gzy)object).d(eyf.e, "test_area.test");
        ((gzy)object).d(eyf.f, "test_area");
        ((gzy)object).d(eyf.g, "google_app.search");
        ((gzy)object).d(eyf.h, "google_app.search_listener");
        ((gzy)object).d(eyf.i, "google_app.browser");
        ((gzy)object).d(eyf.j, "google_app.browser_silent");
        ((gzy)object).d(eyf.k, "assistant.accl");
        ((gzy)object).d(eyf.l, "assistant.pcp");
        ((gzy)object).d(eyf.m, "assistant.weather_at_flight_landing_lo");
        ((gzy)object).d(eyf.n, "assistant.platform");
        ((gzy)object).d(eyf.o, "assistant.dictation");
        ((gzy)object).d(eyf.p, "assistant.translate");
        ((gzy)object).d(eyf.q, "assistant.widget");
        ((gzy)object).d(eyf.r, "assistant.stash");
        ((gzy)object).d(eyf.s, "assistant.ambient");
        ((gzy)object).d(eyf.t, "assistant.recommend");
        ((gzy)object).d(eyf.u, "assistant.routines");
        ((gzy)object).d(eyf.v, "assistant.voice");
        ((gzy)object).d(eyf.w, "assistant.mobile_assistant");
        ((gzy)object).d(eyf.x, "assistant.mobile_assistant_ls");
        ((gzy)object).d(eyf.y, "hindi.search");
        ((gzy)object).d(eyf.z, "hindi.browser");
        ((gzy)object).d(eyf.A, "unknown.silk");
        ((gzy)object).d(eyf.B, "transcription.voice_recognition");
        ((gzy)object).d(eyf.C, "transcription.voice_ime");
        ((gzy)object).d(eyf.D, "assistant.voice_match");
        ((gzy)object).d(eyf.E, "accessibility.voice_access");
        ((gzy)object).d(eyf.F, "google_app.minus_one");
        ((gzy)object).d(eyf.G, "weather.immersive");
        ((gzy)object).d(eyf.H, "weather.widget");
        ((gzy)object).d(eyf.I, "sound_search.now_playing");
        ((gzy)object).d(eyf.J, "sound_search.music_recognition");
        ((gzy)object).d(eyf.K, "google_app.homescreen");
        ((gzy)object).d(eyf.L, "assistant");
        ((gzy)object).d(eyf.M, "assistant.device_registration");
        ((gzy)object).d(eyf.N, "assistant.ambient_classic");
        ((gzy)object).d(eyf.O, "assistant.ambient_bug_report");
        ((gzy)object).d(eyf.P, "assistant.auto");
        ((gzy)object).d(eyf.Q, "assistant_auto_tng.comms");
        ((gzy)object).d(eyf.R, "assistant_auto_tng.mic");
        ((gzy)object).d(eyf.S, "assistant_auto_tng.suggestions");
        ((gzy)object).d(eyf.T, "assistant_auto_tng.morris");
        ((gzy)object).d(eyf.U, "assistant_auto_tng.pop");
        ((gzy)object).d(eyf.V, "assistant.bisto");
        ((gzy)object).d(eyf.W, "assistant.tng_bisto");
        ((gzy)object).d(eyf.X, "assistant.facematch");
        ((gzy)object).d(eyf.Y, "lens");
        ((gzy)object).d(eyf.Z, "lens.browser");
        ((gzy)object).d(eyf.aa, "lens.lvf");
        ((gzy)object).d(eyf.ab, "lens.network_metadata");
        ((gzy)object).d(eyf.ac, "lens.silk_geolocation_real_time");
        ((gzy)object).d(eyf.ad, "assistant.legacy");
        ((gzy)object).d(eyf.ae, "assistant.nga");
        ((gzy)object).d(eyf.af, "assistant.tapas");
        ((gzy)object).d(eyf.ag, "assistant.settings");
        ((gzy)object).d(eyf.ah, "assistant.tng_settings");
        ((gzy)object).d(eyf.ai, "assistant.snapshot");
        ((gzy)object).d(eyf.aj, "assistant.voiceactions");
        ((gzy)object).d(eyf.ak, "assistant.pcp_classic");
        ((gzy)object).d(eyf.al, "assistant.proactiveapi");
        ((gzy)object).d(eyf.am, "assistant.notifications");
        ((gzy)object).d(eyf.an, "assistant.car_lo");
        ((gzy)object).d(eyf.ao, "assistant.clientsync_lo");
        ((gzy)object).d(eyf.ap, "assistant.morris_lo");
        ((gzy)object).d(eyf.aq, "assistant.smartspace_weather_lo");
        ((gzy)object).d(eyf.ar, "assistant.quartz_lo");
        ((gzy)object).d(eyf.as, "lens.lo");
        ((gzy)object).d(eyf.at, "search.embedded_lo");
        ((gzy)object).d(eyf.au, "search.lo");
        ((gzy)object).d(eyf.av, "search.proactive");
        ((gzy)object).d(eyf.aw, "search.proactive_lo");
        ((gzy)object).d(eyf.ax, "search.sidekick_lo");
        ((gzy)object).d(eyf.ay, "services");
        ((gzy)object).d(eyf.az, "services.accl");
        ((gzy)object).d(eyf.aA, "services.accl_lo");
        ((gzy)object).d(eyf.aB, "services.cast");
        ((gzy)object).d(eyf.aC, "services.chime_lo");
        ((gzy)object).d(eyf.aD, "services.clockwork_lo");
        ((gzy)object).d(eyf.aE, "services.clockwork_mic");
        ((gzy)object).d(eyf.aF, "services.contactaffinity");
        ((gzy)object).d(eyf.aG, "services.contextualcards_lo");
        ((gzy)object).d(eyf.aH, "services.lo");
        ((gzy)object).d(eyf.aI, "services.mdd_lo");
        ((gzy)object).d(eyf.aJ, "services.mdi_lib");
        ((gzy)object).d(eyf.aK, "services.silk_lo");
        ((gzy)object).d(eyf.aL, "services.s3_lo");
        ((gzy)object).d(eyf.aM, "services.telephony");
        ((gzy)object).d(eyf.aN, "services.tv_lo");
        ((gzy)object).d(eyf.aO, "services.weather_lo");
        ((gzy)object).d(eyf.aP, "services.wifi");
        ((gzy)object).d(eyf.aQ, "services.co");
        ((gzy)object).d(eyf.aR, "services.clockwork_co");
        ((gzy)object).d(eyf.aS, "creator_studio.record");
        ((gzy)object).d(eyf.aT, "assistant.tng_car_lo");
        ((gzy)object).d(eyf.aU, "search.uri_lo");
        ((gzy)object).d(eyf.aV, "voice_search.lo");
        ((gzy)object).d(eyf.aW, "voice_search.mic");
        ((gzy)object).d(eyf.aX, "assistant.calendar");
        ((gzy)object).d(eyf.aY, "assistant.hubui");
        ((gzy)object).d(eyf.aZ, "assistant.uri_vis");
        ((gzy)object).d(eyf.ba, "sceneviewer.capture");
        ((gzy)object).d(eyf.bb, "assistant.torus");
        ((gzy)object).d(eyf.bc, "web_x.weblayer");
        ((gzy)object).d(eyf.bd, "assistant.text_search");
        ((gzy)object).d(eyf.be, "google_app.silk_geolocation_real_time");
        ((gzy)object).d(eyf.bf, "assistant.silk_geolocation_real_time");
        ((gzy)object).d(eyf.bg, "services.silk_real_time_lo");
        ((gzy)object).d(eyf.bh, "google_app.toast");
        ((gzy)object).d(eyf.bi, "google_app.notifications");
        ((gzy)object).d(eyf.bj, "assistant.connectivity_usonia");
        ((gzy)object).d(eyf.bk, "assistant_titan_tng.hubmode");
        ((gzy)object).d(eyf.bl, "assistant.unattributed_android_trusted_hotword");
        ((gzy)object).d(eyf.bm, "xblend_android.geolocation");
        ((gzy)object).d(eyf.bn, "weather.immersive_real_time");
        ((gzy)object).d(eyf.bo, "robin_android.location");
        ((gzy)object).d(eyf.bp, "robin_android.audio");
        ((gzy)object).d(eyf.bq, "omni.browser");
        ((gzy)object).d(eyf.br, "omni.silk_geolocation_real_time");
        ((gzy)object).d(eyf.bs, "omni.music_search");
        ((gzy)object).d(eyf.bt, "google_app.page_insights_hub");
        ((gzy)object).d(eyf.bu, "google_app.pih_silk_geolocation_real_time");
        ((gzy)object).d(eyf.bv, "assistant.remote_surface_proxy");
        ((gzy)object).d(eyf.bw, "google_app.voice_search_m2");
        object = ((gzy)object).a().k().iterator();
        if (!object.hasNext()) {
            object = hcy.a;
        } else {
            Object object2 = (Map.Entry)object.next();
            Object object3 = (Enum)object2.getKey();
            object2 = object2.getValue();
            fvd.aj(object3, object2);
            object3 = new EnumMap<Enum, Map.Entry>(Collections.singletonMap(object3, object2));
            while (object.hasNext()) {
                Map.Entry entry = (Map.Entry)object.next();
                object2 = (Enum)entry.getKey();
                entry = entry.getValue();
                fvd.aj(object2, entry);
                ((EnumMap)object3).put(object2, entry);
            }
            int n2 = ((EnumMap)object3).size();
            if (n2 != 0) {
                if (n2 != 1) {
                    object = new gzp((EnumMap)object3);
                } else {
                    object = (Map.Entry)fvd.Q(((EnumMap)object3).entrySet());
                    object = hac.j((Enum)object.getKey(), object.getValue());
                }
            } else {
                object = hcy.a;
            }
        }
        a = object;
        object = new gzy();
        ((gzy)object).d("google_app.test", eyf.d);
        ((gzy)object).d("test_area.test", eyf.e);
        ((gzy)object).d("test_area", eyf.f);
        ((gzy)object).d("google_app.search", eyf.g);
        ((gzy)object).d("google_app.search_listener", eyf.h);
        ((gzy)object).d("google_app.browser", eyf.i);
        ((gzy)object).d("google_app.browser_silent", eyf.j);
        ((gzy)object).d("assistant.accl", eyf.k);
        ((gzy)object).d("assistant.pcp", eyf.l);
        ((gzy)object).d("assistant.weather_at_flight_landing_lo", eyf.m);
        ((gzy)object).d("assistant.platform", eyf.n);
        ((gzy)object).d("assistant.dictation", eyf.o);
        ((gzy)object).d("assistant.translate", eyf.p);
        ((gzy)object).d("assistant.widget", eyf.q);
        ((gzy)object).d("assistant.stash", eyf.r);
        ((gzy)object).d("assistant.ambient", eyf.s);
        ((gzy)object).d("assistant.recommend", eyf.t);
        ((gzy)object).d("assistant.routines", eyf.u);
        ((gzy)object).d("assistant.voice", eyf.v);
        ((gzy)object).d("assistant.mobile_assistant", eyf.w);
        ((gzy)object).d("assistant.mobile_assistant_ls", eyf.x);
        ((gzy)object).d("hindi.search", eyf.y);
        ((gzy)object).d("hindi.browser", eyf.z);
        ((gzy)object).d("unknown.silk", eyf.A);
        ((gzy)object).d("transcription.voice_recognition", eyf.B);
        ((gzy)object).d("transcription.voice_ime", eyf.C);
        ((gzy)object).d("assistant.voice_match", eyf.D);
        ((gzy)object).d("accessibility.voice_access", eyf.E);
        ((gzy)object).d("google_app.minus_one", eyf.F);
        ((gzy)object).d("weather.immersive", eyf.G);
        ((gzy)object).d("weather.widget", eyf.H);
        ((gzy)object).d("sound_search.now_playing", eyf.I);
        ((gzy)object).d("sound_search.music_recognition", eyf.J);
        ((gzy)object).d("google_app.homescreen", eyf.K);
        ((gzy)object).d("assistant", eyf.L);
        ((gzy)object).d("assistant.device_registration", eyf.M);
        ((gzy)object).d("assistant.ambient_classic", eyf.N);
        ((gzy)object).d("assistant.ambient_bug_report", eyf.O);
        ((gzy)object).d("assistant.auto", eyf.P);
        ((gzy)object).d("assistant_auto_tng.comms", eyf.Q);
        ((gzy)object).d("assistant_auto_tng.mic", eyf.R);
        ((gzy)object).d("assistant_auto_tng.suggestions", eyf.S);
        ((gzy)object).d("assistant_auto_tng.morris", eyf.T);
        ((gzy)object).d("assistant_auto_tng.pop", eyf.U);
        ((gzy)object).d("assistant.bisto", eyf.V);
        ((gzy)object).d("assistant.tng_bisto", eyf.W);
        ((gzy)object).d("assistant.facematch", eyf.X);
        ((gzy)object).d("lens", eyf.Y);
        ((gzy)object).d("lens.browser", eyf.Z);
        ((gzy)object).d("lens.lvf", eyf.aa);
        ((gzy)object).d("lens.network_metadata", eyf.ab);
        ((gzy)object).d("lens.silk_geolocation_real_time", eyf.ac);
        ((gzy)object).d("assistant.legacy", eyf.ad);
        ((gzy)object).d("assistant.nga", eyf.ae);
        ((gzy)object).d("assistant.tapas", eyf.af);
        ((gzy)object).d("assistant.settings", eyf.ag);
        ((gzy)object).d("assistant.tng_settings", eyf.ah);
        ((gzy)object).d("assistant.snapshot", eyf.ai);
        ((gzy)object).d("assistant.voiceactions", eyf.aj);
        ((gzy)object).d("assistant.pcp_classic", eyf.ak);
        ((gzy)object).d("assistant.proactiveapi", eyf.al);
        ((gzy)object).d("assistant.notifications", eyf.am);
        ((gzy)object).d("assistant.car_lo", eyf.an);
        ((gzy)object).d("assistant.clientsync_lo", eyf.ao);
        ((gzy)object).d("assistant.morris_lo", eyf.ap);
        ((gzy)object).d("assistant.smartspace_weather_lo", eyf.aq);
        ((gzy)object).d("assistant.quartz_lo", eyf.ar);
        ((gzy)object).d("lens.lo", eyf.as);
        ((gzy)object).d("search.embedded_lo", eyf.at);
        ((gzy)object).d("search.lo", eyf.au);
        ((gzy)object).d("search.proactive", eyf.av);
        ((gzy)object).d("search.proactive_lo", eyf.aw);
        ((gzy)object).d("search.sidekick_lo", eyf.ax);
        ((gzy)object).d("services", eyf.ay);
        ((gzy)object).d("services.accl", eyf.az);
        ((gzy)object).d("services.accl_lo", eyf.aA);
        ((gzy)object).d("services.cast", eyf.aB);
        ((gzy)object).d("services.chime_lo", eyf.aC);
        ((gzy)object).d("services.clockwork_lo", eyf.aD);
        ((gzy)object).d("services.clockwork_mic", eyf.aE);
        ((gzy)object).d("services.contactaffinity", eyf.aF);
        ((gzy)object).d("services.contextualcards_lo", eyf.aG);
        ((gzy)object).d("services.lo", eyf.aH);
        ((gzy)object).d("services.mdd_lo", eyf.aI);
        ((gzy)object).d("services.mdi_lib", eyf.aJ);
        ((gzy)object).d("services.silk_lo", eyf.aK);
        ((gzy)object).d("services.s3_lo", eyf.aL);
        ((gzy)object).d("services.telephony", eyf.aM);
        ((gzy)object).d("services.tv_lo", eyf.aN);
        ((gzy)object).d("services.weather_lo", eyf.aO);
        ((gzy)object).d("services.wifi", eyf.aP);
        ((gzy)object).d("services.co", eyf.aQ);
        ((gzy)object).d("services.clockwork_co", eyf.aR);
        ((gzy)object).d("creator_studio.record", eyf.aS);
        ((gzy)object).d("assistant.tng_car_lo", eyf.aT);
        ((gzy)object).d("search.uri_lo", eyf.aU);
        ((gzy)object).d("voice_search.lo", eyf.aV);
        ((gzy)object).d("voice_search.mic", eyf.aW);
        ((gzy)object).d("assistant.calendar", eyf.aX);
        ((gzy)object).d("assistant.hubui", eyf.aY);
        ((gzy)object).d("assistant.uri_vis", eyf.aZ);
        ((gzy)object).d("sceneviewer.capture", eyf.ba);
        ((gzy)object).d("assistant.torus", eyf.bb);
        ((gzy)object).d("web_x.weblayer", eyf.bc);
        ((gzy)object).d("assistant.text_search", eyf.bd);
        ((gzy)object).d("google_app.silk_geolocation_real_time", eyf.be);
        ((gzy)object).d("assistant.silk_geolocation_real_time", eyf.bf);
        ((gzy)object).d("services.silk_real_time_lo", eyf.bg);
        ((gzy)object).d("google_app.toast", eyf.bh);
        ((gzy)object).d("google_app.notifications", eyf.bi);
        ((gzy)object).d("assistant.connectivity_usonia", eyf.bj);
        ((gzy)object).d("assistant_titan_tng.hubmode", eyf.bk);
        ((gzy)object).d("assistant.unattributed_android_trusted_hotword", eyf.bl);
        ((gzy)object).d("xblend_android.geolocation", eyf.bm);
        ((gzy)object).d("weather.immersive_real_time", eyf.bn);
        ((gzy)object).d("robin_android.location", eyf.bo);
        ((gzy)object).d("robin_android.audio", eyf.bp);
        ((gzy)object).d("omni.browser", eyf.bq);
        ((gzy)object).d("omni.silk_geolocation_real_time", eyf.br);
        ((gzy)object).d("omni.music_search", eyf.bs);
        ((gzy)object).d("google_app.page_insights_hub", eyf.bt);
        ((gzy)object).d("google_app.pih_silk_geolocation_real_time", eyf.bu);
        ((gzy)object).d("assistant.remote_surface_proxy", eyf.bv);
        ((gzy)object).d("google_app.voice_search_m2", eyf.bw);
        ((gzy)object).a();
    }
}

