/*
 * Decompiled with CFR 0.152.
 */
public final class idm
implements hrh {
    public static final djt a = new djt("speech.s3.S3StubbyClientConnectorService.");
    public static final djt b = new djt("speech.s3.S3StubbyClientConnectorService/");
    public static final hrf c = new idl(1, null);
    public static final hrf d = new idl(0);
    public static final hrf e = new idl(2, null);
    public static final idm f = new idm();
    public static final djt g = new djt("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
    public final gzx h;
    public final hav i;
    public final hac j;

    private idm() {
        Object object = new gzs();
        ((gzs)object).h("bh-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("cb-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ce-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("cf-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("dj-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ej-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("el-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("gc-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("je-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("lr-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("lu-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ok-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("oz-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("px-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("rg-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sf-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("si-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sl-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sm-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("tm-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("tp-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ue-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("wd-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("yo-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("daily-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("staging-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("super-staging-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("staging-assistant-s3-pa.sandbox.googleapis.com");
        ((gzs)object).h("phil-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test324-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test478-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test189-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test389-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test393-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test67-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test304-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("khromov-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test136-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test143-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test388-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("parrotron-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("thacht-s3-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test215-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test99-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test203-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test218-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test381-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test10-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test424-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test36-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test80-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test145-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("universal-sd-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("id-smartedit-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ikowalski-pod-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ckcz-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test84-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("mnuhn-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("jiangboy-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-test25-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("smart-dictation-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("yf-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("jfmortensen-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("phil-pod-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("yf-pod-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("autopush-assistant-s3-pa.sandbox.googleapis.com");
        ((gzs)object).h("assistant-server-dev-pa.sandbox.googleapis.com");
        ((gzs)object).h("damndaniel-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("pewu-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("thacht-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("zilongh-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("bkutzman-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("alikidwai-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("asfe-shared-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("mkleiner-dev-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("eh-asfe-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("saratan-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("bh-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("cb-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ce-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("cf-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("dj-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ej-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("el-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("gc-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("je-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("lr-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("lu-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ok-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("oz-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("px-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("rg-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sf-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("si-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sl-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("sm-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("tm-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("tp-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ue-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("wd-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("yo-speechs3proto2-pa.sandbox.googleapis.com");
        ((gzs)object).h("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
        this.h = ((gzs)object).g();
        object = new hat();
        ((hat)object).j("https://www.googleapis.com/auth/assistant");
        ((hat)object).j("https://www.googleapis.com/auth/assistant-sdk-prototype");
        ((hat)object).j("https://www.googleapis.com/auth/googlenow");
        ((hat)object).j("https://www.googleapis.com/auth/googleit");
        this.i = ((hat)object).g();
        hrf hrf2 = c;
        hrf hrf3 = d;
        object = e;
        hav.q(hrf2, hrf3, object);
        gzy gzy2 = new gzy();
        gzy2.d("RunBlocking", hrf2);
        gzy2.d("S3Bidi", hrf3);
        gzy2.d("RunBidi", object);
        this.j = gzy2.b();
        new gzy().b();
    }
}

