/*
 * Decompiled with CFR 0.152.
 */
public final class jlg
extends Enum {
    public static final /* enum */ jlg A;
    public static final /* enum */ jlg B;
    public static final /* enum */ jlg C;
    public static final /* enum */ jlg D;
    public static final /* enum */ jlg E;
    public static final /* enum */ jlg F;
    public static final /* enum */ jlg G;
    public static final /* enum */ jlg H;
    public static final /* enum */ jlg I;
    public static final /* enum */ jlg J;
    public static final /* enum */ jlg K;
    public static final /* enum */ jlg L;
    public static final /* enum */ jlg M;
    public static final /* enum */ jlg N;
    public static final /* enum */ jlg O;
    public static final /* enum */ jlg P;
    public static final /* enum */ jlg Q;
    public static final /* enum */ jlg R;
    public static final /* enum */ jlg S;
    public static final /* enum */ jlg T;
    public static final /* enum */ jlg U;
    public static final /* enum */ jlg V;
    public static final /* enum */ jlg W;
    public static final /* enum */ jlg X;
    public static final /* enum */ jlg Y;
    public static final /* enum */ jlg Z;
    public static final /* enum */ jlg a;
    public static final /* enum */ jlg aA;
    public static final /* enum */ jlg aB;
    public static final /* enum */ jlg aC;
    public static final /* enum */ jlg aD;
    public static final /* enum */ jlg aE;
    public static final /* enum */ jlg aF;
    public static final /* enum */ jlg aG;
    public static final /* enum */ jlg aH;
    public static final /* enum */ jlg aI;
    public static final /* enum */ jlg aJ;
    public static final /* enum */ jlg aK;
    public static final /* enum */ jlg aL;
    public static final /* enum */ jlg aM;
    public static final /* enum */ jlg aN;
    public static final /* enum */ jlg aO;
    public static final /* enum */ jlg aP;
    public static final /* enum */ jlg aQ;
    public static final /* enum */ jlg aR;
    public static final /* enum */ jlg aS;
    public static final /* enum */ jlg aT;
    public static final /* enum */ jlg aU;
    public static final /* enum */ jlg aV;
    public static final /* enum */ jlg aW;
    public static final /* enum */ jlg aX;
    public static final /* enum */ jlg aY;
    public static final /* enum */ jlg aZ;
    public static final /* enum */ jlg aa;
    public static final /* enum */ jlg ab;
    public static final /* enum */ jlg ac;
    public static final /* enum */ jlg ad;
    public static final /* enum */ jlg ae;
    public static final /* enum */ jlg af;
    public static final /* enum */ jlg ag;
    public static final /* enum */ jlg ah;
    public static final /* enum */ jlg ai;
    public static final /* enum */ jlg aj;
    public static final /* enum */ jlg ak;
    public static final /* enum */ jlg al;
    public static final /* enum */ jlg am;
    public static final /* enum */ jlg an;
    public static final /* enum */ jlg ao;
    public static final /* enum */ jlg ap;
    public static final /* enum */ jlg aq;
    public static final /* enum */ jlg ar;
    public static final /* enum */ jlg as;
    public static final /* enum */ jlg at;
    public static final /* enum */ jlg au;
    public static final /* enum */ jlg av;
    public static final /* enum */ jlg aw;
    public static final /* enum */ jlg ax;
    public static final /* enum */ jlg ay;
    public static final /* enum */ jlg az;
    public static final /* enum */ jlg b;
    public static final /* enum */ jlg ba;
    private static final jlg[] bc;
    public static final /* enum */ jlg c;
    public static final /* enum */ jlg d;
    public static final /* enum */ jlg e;
    public static final /* enum */ jlg f;
    public static final /* enum */ jlg g;
    public static final /* enum */ jlg h;
    public static final /* enum */ jlg i;
    public static final /* enum */ jlg j;
    public static final /* enum */ jlg k;
    public static final /* enum */ jlg l;
    public static final /* enum */ jlg m;
    public static final /* enum */ jlg n;
    public static final /* enum */ jlg o;
    public static final /* enum */ jlg p;
    public static final /* enum */ jlg q;
    public static final /* enum */ jlg r;
    public static final /* enum */ jlg s;
    public static final /* enum */ jlg t;
    public static final /* enum */ jlg u;
    public static final /* enum */ jlg v;
    public static final /* enum */ jlg w;
    public static final /* enum */ jlg x;
    public static final /* enum */ jlg y;
    public static final /* enum */ jlg z;
    final String bb;

    static {
        jlg jlg2;
        jlg jlg3;
        jlg jlg4;
        jlg jlg5;
        jlg jlg6;
        jlg jlg7;
        jlg jlg8;
        jlg jlg9;
        jlg jlg10;
        jlg jlg11;
        jlg jlg12;
        jlg jlg13;
        jlg jlg14;
        jlg jlg15;
        jlg jlg16;
        jlg jlg17;
        jlg jlg18;
        jlg jlg19;
        jlg jlg20;
        jlg jlg21;
        jlg jlg22;
        jlg jlg23;
        jlg jlg24;
        jlg jlg25;
        jlg jlg26;
        jlg jlg27;
        jlg jlg28;
        jlg jlg29;
        jlg jlg30;
        jlg jlg31;
        jlg jlg32;
        jlg jlg33;
        jlg jlg34;
        jlg jlg35;
        jlg jlg36;
        jlg jlg37;
        jlg jlg38;
        jlg jlg39;
        jlg jlg40;
        jlg jlg41;
        jlg jlg42;
        jlg jlg43;
        jlg jlg44;
        jlg jlg45;
        jlg jlg46;
        jlg jlg47;
        jlg jlg48;
        jlg jlg49;
        jlg jlg50;
        jlg jlg51;
        jlg jlg52;
        jlg jlg53;
        jlg jlg54;
        jlg jlg55;
        jlg jlg56;
        jlg jlg57;
        jlg jlg58;
        jlg jlg59;
        jlg jlg60;
        jlg jlg61;
        jlg jlg62;
        jlg jlg63;
        jlg jlg64;
        jlg jlg65;
        jlg jlg66;
        jlg jlg67;
        jlg jlg68;
        jlg jlg69;
        jlg jlg70;
        jlg jlg71;
        jlg jlg72;
        jlg jlg73;
        jlg jlg74;
        jlg jlg75;
        jlg jlg76;
        jlg jlg77;
        jlg jlg78;
        jlg jlg79;
        jlg jlg80;
        jlg jlg81;
        jlg jlg82;
        jlg jlg83;
        jlg jlg84;
        jlg jlg85;
        jlg jlg86;
        jlg jlg87;
        jlg jlg88;
        jlg jlg89;
        jlg jlg90;
        jlg jlg91;
        jlg jlg92;
        jlg jlg93;
        jlg jlg94;
        jlg jlg95;
        jlg jlg96;
        jlg jlg97;
        jlg jlg98;
        jlg jlg99;
        jlg jlg100;
        jlg jlg101;
        jlg jlg102;
        jlg jlg103;
        jlg jlg104;
        jlg jlg105;
        jlg jlg106;
        a = jlg106 = new jlg("TLS_RSA_WITH_NULL_MD5", 0, "SSL_RSA_WITH_NULL_MD5", null);
        b = jlg105 = new jlg("TLS_RSA_WITH_NULL_SHA", 1, "SSL_RSA_WITH_NULL_SHA", null);
        c = jlg104 = new jlg("TLS_RSA_EXPORT_WITH_RC4_40_MD5", 2, "SSL_RSA_EXPORT_WITH_RC4_40_MD5", null);
        d = jlg103 = new jlg("TLS_RSA_WITH_RC4_128_MD5", 3, "SSL_RSA_WITH_RC4_128_MD5", null);
        e = jlg102 = new jlg("TLS_RSA_WITH_RC4_128_SHA", 4, "SSL_RSA_WITH_RC4_128_SHA", null);
        f = jlg101 = new jlg("TLS_RSA_EXPORT_WITH_DES40_CBC_SHA", 5, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA", null);
        g = jlg100 = new jlg("TLS_RSA_WITH_DES_CBC_SHA", 6, "SSL_RSA_WITH_DES_CBC_SHA", null);
        h = jlg99 = new jlg("TLS_RSA_WITH_3DES_EDE_CBC_SHA", 7, "SSL_RSA_WITH_3DES_EDE_CBC_SHA", null);
        i = jlg98 = new jlg("TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA", 8, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA", null);
        j = jlg97 = new jlg("TLS_DHE_DSS_WITH_DES_CBC_SHA", 9, "SSL_DHE_DSS_WITH_DES_CBC_SHA", null);
        k = jlg96 = new jlg("TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA", 10, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA", null);
        l = jlg95 = new jlg("TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA", 11, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA", null);
        m = jlg94 = new jlg("TLS_DHE_RSA_WITH_DES_CBC_SHA", 12, "SSL_DHE_RSA_WITH_DES_CBC_SHA", null);
        n = jlg93 = new jlg("TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA", 13, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA", null);
        o = jlg92 = new jlg("TLS_DH_anon_EXPORT_WITH_RC4_40_MD5", 14, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5", null);
        p = jlg91 = new jlg("TLS_DH_anon_WITH_RC4_128_MD5", 15, "SSL_DH_anon_WITH_RC4_128_MD5", null);
        q = jlg90 = new jlg("TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA", 16, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA", null);
        r = jlg89 = new jlg("TLS_DH_anon_WITH_DES_CBC_SHA", 17, "SSL_DH_anon_WITH_DES_CBC_SHA", null);
        s = jlg88 = new jlg("TLS_DH_anon_WITH_3DES_EDE_CBC_SHA", 18, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA", null);
        t = jlg87 = new jlg("TLS_KRB5_WITH_DES_CBC_SHA", 19, "TLS_KRB5_WITH_DES_CBC_SHA", null);
        u = jlg86 = new jlg("TLS_KRB5_WITH_3DES_EDE_CBC_SHA", 20, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA", null);
        v = jlg85 = new jlg("TLS_KRB5_WITH_RC4_128_SHA", 21, "TLS_KRB5_WITH_RC4_128_SHA", null);
        w = jlg84 = new jlg("TLS_KRB5_WITH_DES_CBC_MD5", 22, "TLS_KRB5_WITH_DES_CBC_MD5", null);
        x = jlg83 = new jlg("TLS_KRB5_WITH_3DES_EDE_CBC_MD5", 23, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5", null);
        y = jlg82 = new jlg("TLS_KRB5_WITH_RC4_128_MD5", 24, "TLS_KRB5_WITH_RC4_128_MD5", null);
        z = jlg81 = new jlg("TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA", 25, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA", null);
        A = jlg80 = new jlg("TLS_KRB5_EXPORT_WITH_RC4_40_SHA", 26, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA", null);
        B = jlg79 = new jlg("TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5", 27, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5", null);
        C = jlg78 = new jlg("TLS_KRB5_EXPORT_WITH_RC4_40_MD5", 28, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5", null);
        D = jlg77 = new jlg("TLS_RSA_WITH_AES_128_CBC_SHA", 29, "TLS_RSA_WITH_AES_128_CBC_SHA", null);
        E = jlg76 = new jlg("TLS_DHE_DSS_WITH_AES_128_CBC_SHA", 30, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA", null);
        F = jlg75 = new jlg("TLS_DHE_RSA_WITH_AES_128_CBC_SHA", 31, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA", null);
        G = jlg74 = new jlg("TLS_DH_anon_WITH_AES_128_CBC_SHA", 32, "TLS_DH_anon_WITH_AES_128_CBC_SHA", null);
        H = jlg73 = new jlg("TLS_RSA_WITH_AES_256_CBC_SHA", 33, "TLS_RSA_WITH_AES_256_CBC_SHA", null);
        I = jlg72 = new jlg("TLS_DHE_DSS_WITH_AES_256_CBC_SHA", 34, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA", null);
        J = jlg71 = new jlg("TLS_DHE_RSA_WITH_AES_256_CBC_SHA", 35, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA", null);
        K = jlg70 = new jlg("TLS_DH_anon_WITH_AES_256_CBC_SHA", 36, "TLS_DH_anon_WITH_AES_256_CBC_SHA", null);
        L = jlg69 = new jlg("TLS_RSA_WITH_NULL_SHA256", 37, "TLS_RSA_WITH_NULL_SHA256", null);
        M = jlg68 = new jlg("TLS_RSA_WITH_AES_128_CBC_SHA256", 38, "TLS_RSA_WITH_AES_128_CBC_SHA256", null);
        N = jlg67 = new jlg("TLS_RSA_WITH_AES_256_CBC_SHA256", 39, "TLS_RSA_WITH_AES_256_CBC_SHA256", null);
        O = jlg66 = new jlg("TLS_DHE_DSS_WITH_AES_128_CBC_SHA256", 40, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256", null);
        P = jlg65 = new jlg("TLS_DHE_RSA_WITH_AES_128_CBC_SHA256", 41, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256", null);
        Q = jlg64 = new jlg("TLS_DHE_DSS_WITH_AES_256_CBC_SHA256", 42, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256", null);
        R = jlg63 = new jlg("TLS_DHE_RSA_WITH_AES_256_CBC_SHA256", 43, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256", null);
        S = jlg62 = new jlg("TLS_DH_anon_WITH_AES_128_CBC_SHA256", 44, "TLS_DH_anon_WITH_AES_128_CBC_SHA256", null);
        T = jlg61 = new jlg("TLS_DH_anon_WITH_AES_256_CBC_SHA256", 45, "TLS_DH_anon_WITH_AES_256_CBC_SHA256", null);
        U = jlg60 = new jlg("TLS_RSA_WITH_AES_128_GCM_SHA256", 46, "TLS_RSA_WITH_AES_128_GCM_SHA256", null);
        V = jlg59 = new jlg("TLS_RSA_WITH_AES_256_GCM_SHA384", 47, "TLS_RSA_WITH_AES_256_GCM_SHA384", null);
        W = jlg58 = new jlg("TLS_DHE_RSA_WITH_AES_128_GCM_SHA256", 48, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256", null);
        X = jlg57 = new jlg("TLS_DHE_RSA_WITH_AES_256_GCM_SHA384", 49, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384", null);
        Y = jlg56 = new jlg("TLS_DHE_DSS_WITH_AES_128_GCM_SHA256", 50, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256", null);
        Z = jlg55 = new jlg("TLS_DHE_DSS_WITH_AES_256_GCM_SHA384", 51, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384", null);
        aa = jlg54 = new jlg("TLS_DH_anon_WITH_AES_128_GCM_SHA256", 52, "TLS_DH_anon_WITH_AES_128_GCM_SHA256", null);
        ab = jlg53 = new jlg("TLS_DH_anon_WITH_AES_256_GCM_SHA384", 53, "TLS_DH_anon_WITH_AES_256_GCM_SHA384", null);
        ac = jlg52 = new jlg("TLS_EMPTY_RENEGOTIATION_INFO_SCSV", 54, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV", null);
        ad = jlg51 = new jlg("TLS_ECDH_ECDSA_WITH_NULL_SHA", 55, "TLS_ECDH_ECDSA_WITH_NULL_SHA", null);
        ae = jlg50 = new jlg("TLS_ECDH_ECDSA_WITH_RC4_128_SHA", 56, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA", null);
        af = jlg49 = new jlg("TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", 57, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA", null);
        ag = jlg48 = new jlg("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA", 58, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA", null);
        ah = jlg47 = new jlg("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA", 59, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA", null);
        ai = jlg46 = new jlg("TLS_ECDHE_ECDSA_WITH_NULL_SHA", 60, "TLS_ECDHE_ECDSA_WITH_NULL_SHA", null);
        aj = jlg45 = new jlg("TLS_ECDHE_ECDSA_WITH_RC4_128_SHA", 61, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA", null);
        ak = jlg44 = new jlg("TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA", 62, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA", null);
        al = jlg43 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", 63, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA", null);
        am = jlg42 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", 64, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA", null);
        an = jlg41 = new jlg("TLS_ECDH_RSA_WITH_NULL_SHA", 65, "TLS_ECDH_RSA_WITH_NULL_SHA", null);
        ao = jlg40 = new jlg("TLS_ECDH_RSA_WITH_RC4_128_SHA", 66, "TLS_ECDH_RSA_WITH_RC4_128_SHA", null);
        ap = jlg39 = new jlg("TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", 67, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA", null);
        aq = jlg38 = new jlg("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA", 68, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA", null);
        ar = jlg37 = new jlg("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA", 69, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA", null);
        as = jlg36 = new jlg("TLS_ECDHE_RSA_WITH_NULL_SHA", 70, "TLS_ECDHE_RSA_WITH_NULL_SHA", null);
        at = jlg35 = new jlg("TLS_ECDHE_RSA_WITH_RC4_128_SHA", 71, "TLS_ECDHE_RSA_WITH_RC4_128_SHA", null);
        au = jlg34 = new jlg("TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", 72, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA", null);
        av = jlg33 = new jlg("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", 73, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", null);
        aw = jlg32 = new jlg("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", 74, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA", null);
        ax = jlg31 = new jlg("TLS_ECDH_anon_WITH_NULL_SHA", 75, "TLS_ECDH_anon_WITH_NULL_SHA", null);
        ay = jlg30 = new jlg("TLS_ECDH_anon_WITH_RC4_128_SHA", 76, "TLS_ECDH_anon_WITH_RC4_128_SHA", null);
        az = jlg29 = new jlg("TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA", 77, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA", null);
        aA = jlg28 = new jlg("TLS_ECDH_anon_WITH_AES_128_CBC_SHA", 78, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA", null);
        aB = jlg27 = new jlg("TLS_ECDH_anon_WITH_AES_256_CBC_SHA", 79, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA", null);
        aC = jlg26 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", 80, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256", null);
        aD = jlg25 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", 81, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384", null);
        aE = jlg24 = new jlg("TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256", 82, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256", null);
        aF = jlg23 = new jlg("TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384", 83, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384", null);
        aG = jlg22 = new jlg("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", 84, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256", null);
        aH = jlg21 = new jlg("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", 85, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384", null);
        aI = jlg20 = new jlg("TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256", 86, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256", null);
        aJ = jlg19 = new jlg("TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384", 87, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384", null);
        aK = jlg18 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", 88, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", null);
        aL = jlg17 = new jlg("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", 89, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", null);
        aM = jlg16 = new jlg("TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256", 90, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256", null);
        aN = jlg15 = new jlg("TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384", 91, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384", null);
        aO = jlg14 = new jlg("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", 92, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", null);
        aP = jlg13 = new jlg("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", 93, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", null);
        aQ = jlg12 = new jlg("TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256", 94, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256", null);
        aR = jlg11 = new jlg("TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384", 95, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384", null);
        aS = jlg10 = new jlg("TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256", 96, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        aT = jlg9 = new jlg("TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256", 97, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        aU = jlg8 = new jlg("TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256", 98, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        aV = jlg7 = new jlg("TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256", 99, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        aW = jlg6 = new jlg("TLS_AES_128_GCM_SHA256", 100, "TLS_AES_128_GCM_SHA256");
        aX = jlg5 = new jlg("TLS_AES_256_GCM_SHA384", 101, "TLS_AES_256_GCM_SHA384");
        aY = jlg4 = new jlg("TLS_CHACHA20_POLY1305_SHA256", 102, "TLS_CHACHA20_POLY1305_SHA256");
        aZ = jlg3 = new jlg("TLS_AES_128_CCM_SHA256", 103, "TLS_AES_128_CCM_SHA256");
        ba = jlg2 = new jlg("TLS_AES_128_CCM_8_SHA256", 104, "TLS_AES_128_CCM_8_SHA256");
        bc = new jlg[]{jlg106, jlg105, jlg104, jlg103, jlg102, jlg101, jlg100, jlg99, jlg98, jlg97, jlg96, jlg95, jlg94, jlg93, jlg92, jlg91, jlg90, jlg89, jlg88, jlg87, jlg86, jlg85, jlg84, jlg83, jlg82, jlg81, jlg80, jlg79, jlg78, jlg77, jlg76, jlg75, jlg74, jlg73, jlg72, jlg71, jlg70, jlg69, jlg68, jlg67, jlg66, jlg65, jlg64, jlg63, jlg62, jlg61, jlg60, jlg59, jlg58, jlg57, jlg56, jlg55, jlg54, jlg53, jlg52, jlg51, jlg50, jlg49, jlg48, jlg47, jlg46, jlg45, jlg44, jlg43, jlg42, jlg41, jlg40, jlg39, jlg38, jlg37, jlg36, jlg35, jlg34, jlg33, jlg32, jlg31, jlg30, jlg29, jlg28, jlg27, jlg26, jlg25, jlg24, jlg23, jlg22, jlg21, jlg20, jlg19, jlg18, jlg17, jlg16, jlg15, jlg14, jlg13, jlg12, jlg11, jlg10, jlg9, jlg8, jlg7, jlg6, jlg5, jlg4, jlg3, jlg2};
    }

    /*
     * WARNING - Possible parameter corruption
     * WARNING - void declaration
     */
    private jlg() {
        void var3_2;
        void var2_-1;
        void var1_-1;
        this.bb = var3_2;
    }

    /*
     * WARNING - void declaration
     */
    private jlg() {
        void var3_2;
        void var1_-1;
        this.bb = var3_2;
    }

    public static jlg a(String string) {
        return Enum.valueOf(jlg.class, string);
    }

    public static jlg[] values() {
        return (jlg[])bc.clone();
    }
}

